name: "Version Bump"
description: "Will bump current version"
author: "FB Awana"
inputs:
  github_token: # The github token
    required: true
    description: "The users github token"
  version:
    required: false
    description: "Optional Override of version"
outputs:
  tag: # tag of output
    description: "The tag name to be created"
  release_name: # release_name of output
    description: "What the release should be"
  body: # body of output
    description: "What should be put on the release"
runs:
  using: "node16"
  main: "dist/index.js"
